### ISSUE TITLE
Dumplings recipe listed on the Wiki is incorrect

### ISSUE THREAD

**Issue by MrTibbs92** [newhoryzon/farmers-delight-fabric#107]
Wiki shows wheat dough needed to create the dumplings but it is actually the Raw Pasta that is needed. Also, you could update it to say RAW Beef as there are multiple kinds of beef in the mod.

**Comment by Zifiv** [comment]
Hello @MrTibbs92,

The wiki is on the official forge mod, it is not maintained by me, if you show any issue on it, you can ask for it on the forge repository : https://github.com/vectorwing/FarmersDelight/issues .

About the dumplings recipe, what's version are you using, because actualy the last version of Farmer's Delight fabric for 1.19.2 and 1.18.2 have the correct recipe.
