### ISSUE TITLE
Make Wood chopping use the general logs tag

### ISSUE THREAD

**Issue by wildjerry** [newhoryzon/farmers-delight-fabric#114]
Hi, I've noticed an issue with how Farmer's Delight integrates with other mods like Biomes a plenty-namely, that it doesn't(at least for wood chopping recipes,as far as I can tell). I tried to use Cherry Logs(byg:cherry_log) to get tree bark, but it doesn't work. Birch wood works fine.

**Comment by Zifiv** [comment]
Hello @wildjerry,

The logs chopping in cutting board isn't easy as you think, because it's a recipe for each logs block if I add a recipe that can take all logs present in the tag, it will produce for every logs the same stripped logs.
Isn't at me to add the compatibility for others mods, because they can name their stripped version how they want for the block, so ask for mods developer to add compatibility with cutting board.

I'm currently working on a solution that can dynamically adds recipes for all logs block in common logs tag, but this is not my priority.

Btw, it's a duplicate from another issue, use the new one to see the advancement of the feature #149.
