### ISSUE TITLE
Server boot error 1.19.2

### ISSUE THREAD

**Issue by Djoeliejoes** [newhoryzon/farmers-delight-fabric#140]
I am not sure if I should post this here or on botany pots' page, so please correct me if I'm wrong. This error is not game breaking as I can still play on my server, but it is an error nonetheless.
Log:
https://mclo.gs/TGtln3C
(error starts at line 194)

**Comment by Zifiv** [comment]
Hello @Djoeliejoes,

It's in Botany Pots side. It seems that they are trying to point an unknown block `farmersdelight:rice`.
This error is caused by the difference between forge and fabric version of Farmer's Delight (I tried to have no difference but it's not all up-to-date already).

In Forge version, rice crops block has been renamed in **`rice`**, but I've not already done this changes in the fabric version (a change like that, can break world that was created before the rename), I'll develop the rename to have parity with Forge version soon, but for now, it's Botany Pots' developers that should use the right block name for fabric version of Farmer's Delight that is `farmersdelight:rice_crop`.
