### ISSUE TITLE
Mod 1.20.1 Update?

### ISSUE THREAD

**Issue by lostopkk** [newhoryzon/farmers-delight-fabric#159]

**Comment by Zifiv** [comment]
Hello @lostopkk,

Just to be clear, the more you ask me "1.20 update" (and btw without any correct asking; maybe a simple hello, or a complete sentence with a "please") the less It makes me want to take, the very little of my free time I have, to develop it...

So please, wait and be patient, the 1.20 is out since less than two week... Issue tracker isn't for asking upgrades for new Minecraft update, I will do it when I will have the time.

**Comment by lostopkk** [comment]
> Hello @lostopkk,
> 
> Just to be clear, the more you ask me "1.20 update" (and btw without any correct asking; maybe a simple hello, or a complete sentence with a "please") the less It makes me want to take, the very little of my free time I have, to develop it...
> 
> So please, wait and be patient, the 1.20 is out since less than two week... Issue tracker isn't for asking upgrades for new Minecraft update, I will do it when I will have the time.

sorry about that, didn't mean to be rude it's just hard talking to developers and the issue tracker is always a good place to see if the project is still in development... take your time! i love this mod just wanted to know if it has been stopped or discontinued.
