### ISSUE TITLE
update to new version

### ISSUE THREAD

**Issue by Nude-Zenpai** [newhoryzon/farmers-delight-fabric#160]
Minecraft 1.20.x update?

**Comment by Zifiv** [comment]
Hello @Nude-Zenpai,

Just to be clear, the more you ask me "1.20 update" (and btw without any correct asking; maybe a simple hello, or a complete sentence with a "please") the less It makes me want to take, the very little of my free time I have, to develop it...

So please, wait and be patient, the 1.20 is out since less than two week... Issue tracker isn't for asking upgrades for new Minecraft update, I will do it when I will have the time.
