### ISSUE TITLE
Planned 1.20.1 update?

### ISSUE THREAD

**Issue by Therkelsen** [newhoryzon/farmers-delight-fabric#161]
Hey!

Do you plan to update this to 1.20.1 in the near future?

**Comment by Zifiv** [comment]
Hello @Therkelsen,

Just to be clear, the more you ask me "1.20 update" (and btw without any correct asking; maybe a simple hello, or a complete sentence with a "please") the less It makes me want to take, the very little of my free time I have, to develop it...

So please, wait and be patient... Issue tracker isn't for asking upgrades for new Minecraft update, I will do it when I will have the time.

**Comment by Therkelsen** [comment]
It was not meant to sound rude, sorry! :)

**Comment by Zifiv** [comment]
Sorry it was just a "copy-paste" response when people ask me for 1.20 updates, it's very exhausting to see people cannot just wait for updating the mod.

I've not realy read the content of your message at first, but now I did, I'm sorry because unlike everyone else asking for update, you asked it "correctly", not with just like "1.20 update ?".

So to make you a better answer, I'm currently working on it (today) and with fixes many other issues; a release will be done today.
