### ISSUE TITLE
[1.19.2 - 1.3.10] Clicking recipe book inside Cooking Pot causes game to crash.

### ISSUE THREAD

**Issue by TheSofas** [newhoryzon/farmers-delight-fabric#178]
Clicking the Recipe Book inside of the Cooking Pot will instantly crash the game to desktop. This was on 1.19.2-1.3.10 playing on the Medieval Minecraft Modpack. Crash log attached.

[crash-2023-07-17_07.04.42-client.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/12069098/crash-2023-07-17_07.04.42-client.txt)

**Comment by Zifiv** [comment]
Hello @TheSofas,

Thank you for reporting this issue.

Your shouldn't have the recipe book into cooking pot, the functionality is under development and not finished yet.
This is a bug caused by the mod "Recipe Book Delight" that add recipe book for Farmer's Delight fabric version but that is not upgraded to the lastest version of FD (1.3.10 here).

Ask to the author of Recipe Book Delight to tell him upgrade his addon.
