### ISSUE TITLE
Crash every time trying to use recipe book in cooking pot 

### ISSUE THREAD

**Issue by EmiTheWinged** [newhoryzon/farmers-delight-fabric#179]
Not sure if it will have any impact but in modpack Medieval Minecraft (Fabric) 
If you open the recipe book (the green one ) in a cooking pot the game will crash every single time. The mod is apparently updated by i never tried to open that recipe book before so i don't know if its a new bug or not.

**Comment by Linguardium** [comment]
posting a crashlog to a log service like https://mclo.gs/ or similar and then providing the link here would allow the developer to look at the log and determine where the crash is occurring in the code

**Comment by Zifiv** [comment]
Hello @EmiTheWinged,

Like @Linguardium said, it's a duplicate with #178, this is bug caused by another mod that changes the code of Farmer's Delight to add the recipe book.
This mod should be upgraded for the newest version of Farmer's Delight fabric, you can ask to the autor in the issue tracker of Recipe Book Delight : https://github.com/melontini/recipe-book-delight/issues.
