### ISSUE TITLE
Missing features from 1.20 FD Forge

### ISSUE THREAD

**Issue by ExDrill** [newhoryzon/farmers-delight-fabric#184]
This isn't really much of an issue, rather a question. Are PRs allowed for implementing some of the missing features and changes done in the 1.20 Forge port of Farmer's Delight?

**Comment by Zifiv** [comment]
Hello @ExDrill,

All features and changes in forge version is in development on my side, it is unncessary to create PRs because some things are already done, but not release because I wait until all is finished before release.
You can try to publish your PR (from "develop" branch) and if I've not started yet or already developed the feature you added, I will merge it ;) !
Thanks your wanted helping, it's really appreciated.
