### ISSUE TITLE
things i put in pan wont show

### ISSUE THREAD

**Issue by happy0catte** [newhoryzon/farmers-delight-fabric#192]
i put somthing to pan but it wont show

**Comment by AntonioCrazi** [comment]
it's happening to me too

**Comment by DaCooladeMan** [comment]
It's happened to me too. Zifiv made a post about it in the issues tab, somewhere below this post. The skillet animation is invisible when used as block entity, he says. The bug is ready to-do which I think means ready to be fixed. I don't know, I don't normally use GitHub, so I don't know these things. Hopefully it's fixed in the next few days though.

**Comment by Zifiv** [comment]
Hello @happy0catte,

Thank you for reporting the issue, it seems that is the same error than #177. I close this issue and you can add some information of your bug in the original issue I've mentionned just before.
