### ISSUE TITLE
[Contribution] es_es update!

### ISSUE THREAD

**Issue by kxkxrxtx** [newhoryzon/farmers-delight-fabric#24]
Hi! I'm really thankful to the last translator that updated the mod to my language, but frankly the mod was really outdated. Also there were lots of items, blocks, advancements, etc. that were not translated at all, so I have updated the json for (Spain) spanish users. Here you are!
[es_es.json](https://gist.github.com/kxkxrxtx/d8f5f8256775aada77ae6aaa67423f2c)
I would be glad to help in future releases if you like!

**Comment by kxkxrxtx** [comment]
Something like this? I'm sorry, I don't have any notion of github, so if there's something wrong just tell me n_n
https://gist.github.com/kxkxrxtx/d8f5f8256775aada77ae6aaa67423f2c

**Comment by Zifiv** [comment]
It's perfect like that 👍!

**Comment by kxkxrxtx** [comment]
Wow, loving the latest update! Finally on pair with latest But I was curious if there's some concerning about my contribution. Maybe I should post it first in the original mod? Anyway, here's the latest translation update, which now is fully updated to the original en_us.json

https://gist.github.com/kxkxrxtx/d9aa60c3562b8ee8f8374ef3da6be2dd

**Comment by Zifiv** [comment]
Like you said, I think that it's a good idea to post your modification in the original mod (forge version) issue tracker.

Because while I will update from the new version original mod, if for some reason there is changes in the spanish translation, I will just reuse the file from the original mod.
I can add your changes in the next release, but I recommand you to ask your changes in the original mod too, to ensure that your changes will not being lost in the futur ;).
