### ISSUE TITLE
Rich Soil Presence of The Footsep Compatibility

### ISSUE THREAD

**Issue by ardissaps** [newhoryzon/farmers-delight-fabric#25]
Would you like to add [Presence of the Footstep](https://modrinth.com/mod/presence-footsteps) ound on rich soil footstep?
![image](https://user-images.githubusercontent.com/82106625/176351648-67d2dc39-27f3-4c06-95cd-c480996bbc25.png)
For now I only found full block that does not produce sound when stepped (and some crop when we passthrough), other than that works just fine.

**Comment by ardissaps** [comment]
Thank you, it works. But I have question, why only soil need the config? (as some other without config have sound)

**Comment by Zifiv** [comment]
Do you have sound while you passthrough **organic compost** block ?

**Comment by ardissaps** [comment]
Currently I only add these block:
![image](https://user-images.githubusercontent.com/82106625/178407648-5b843efc-900f-4bf2-bb7d-f9c6aafe87cf.png)

> Do you have sound while you passthrough **organic compost** block ?

Organic Compost already have sound without editing anything :
![image](https://user-images.githubusercontent.com/82106625/178407961-5936708f-7979-4989-9a33-248806a3955d.png)

**Comment by Zifiv** [comment]
Ok thanks you, this is weird...

Maybe Presence of Footstep use the sound of the block (the sound he make while placing it) to automaticaly determine the sound used while passthrough.
For Organic compost it's the same sound as Dirt, but for Rich soil it's the sound of Rooted Dirt.

Can you tell me if there is a sound while passthrough on Rooted dirt ? If not, you can create a new ticket on Presence of Footstep to add sound of type "dirt" on block that use Rooted dirt sound on Minecraft.

**Comment by ardissaps** [comment]
Vanilla Rooted Dirt does have sound.
![image](https://user-images.githubusercontent.com/82106625/178642909-8bfe4293-beae-4480-82a3-e32920b5e46e.png)

**Comment by Zifiv** [comment]
Okey, very weird, I don't know why there is sound for Organic compost and not for Rich soil... but I think that what I supposed in my last answer is true (and our test is not usefull, because the default config specifies the sound for rooted dirt), maybe it can be usefull to ask it to the author of _Presence Footsteps_.

So in all case, I'll add by default the integration of _Presence Footsteps_ by adding Rich soil and his farmland version to the assets of Farmer's Delight.

Thanks your @ardissaps again to answering my questions 😃.
